export default {

  // There is a list of specific pages that map to these "t" values.
  categoryMap: {
    'arts': 'arts',
    'baby-and-child': 'bestbuys',
    'bills': 'bills',
    'books': 'books',
    'business': 'business',
    'christmas-ibuys': 'bestbuys',
    'columnists': 'opinion',
    'comment': 'opinion',
    'cricket': 'cricket',
    'culture': 'culture',
    'editor': 'opinion',
    'education': 'education',
    'environment': 'environment',
    'ethical-money': 'ethicalmoney',
    'fashion-and-beauty': 'bestbuys',
    'film': 'film',
    'food-and-drink': 'foodanddrink',
    'food-and-drink-ibuys': 'bestbuys',
    'football': 'football',
    'formula-one': 'formulaone',
    'gaming': 'gaming',
    'health': 'health',
    'home-and-garden': 'bestbuys',
    'homes-and-gardens': 'homesandgarden',
    'ibuys': 'bestbuys',
    'inews-lifestyle': 'lifestyle',
    'investing': 'investing',
    'long-reads': 'features',
    'money': 'money',
    'motoring': 'motoring',
    'music': 'music',
    'news': 'news',
    'opinion': 'opinion',
    'pensions-and-retirement': 'retirement',
    'people': 'people',
    'politics': 'politics',
    'property-and-mortgages': 'property',
    'radio': 'radio',
    'rugby-union': 'rugbyunion',
    'saving-and-banking': 'savings',
    'science': 'science',
    'scotland': 'scotland',
    'small-business': 'smallbusiness',
    'sport': 'sport',
    'tech': 'bestbuys',
    'technology': 'technology',
    'television': 'television',
    'travel': 'travel',
    'travel-and-outdoor': 'bestbuys',
    'uk': 'uk',
    'wellbeing': 'wellbeing',
    'women': 'women',
    'world': 'world',
    'your-views': 'opinion',
  },

};
